version: "3"

services:
  postgres-db:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: test1234
    ports:
      - "15432:5432"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"

  grafana:
    image: grafana/grafana-oss:10.0.12
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  backend-api:
    image: backend-api
    build:
      context: ./
      dockerfile: deploy.dockerfile
    ports:
      - "17771:7771"
      - "17779:7779"

volumes:
  grafana-data:
